steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hackernews:1.0.$BUILD_ID', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hackernews:1.0.$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - hackernews
  - web=gcr.io/$PROJECT_ID/hackernews:1.0.$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asis-northeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'